apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-deploy
  labels:
    app: healthcare-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-eta-app
  template:
    metadata:
      labels:
        app: healthcare-eta-app
    spec:
      containers:
      - name: healthcare-eta-container
        image: waasifahmed/healthcare-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-np-service
  labels:
    app: healthcare-eta-app
spec:
  selector:
    app: healthcare-eta-app
  type: NodePort  # Keep the type as NodePort
  ports:
  - port: 8082      # The port exposed within the cluster
    targetPort: 8082 # The port the container is listening on
    # nodePort: 310
